import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.keyword.excel.ExcelKeywords as ExcelKeywords

int j = GlobalVariable.excel_col
String excelFile01 = GlobalVariable.excel_path
// Set Login Data To Excel File
workbook01 = ExcelKeywords.getWorkbook(excelFile01)
login = ExcelKeywords.getExcelSheet(workbook01, 'login')
ExcelKeywords.setValueToCellByAddress(login, 'A1', 'round_id')
ExcelKeywords.setValueToCellByIndex(login, j, 0, GlobalVariable.round_id)
ExcelKeywords.setValueToCellByAddress(login, 'B1', 'balance')
ExcelKeywords.setValueToCellByIndex(login, j, 1, GlobalVariable.login_balance)
ExcelKeywords.setValueToCellByAddress(login, 'C1', 'currency')
ExcelKeywords.setValueToCellByIndex(login, j, 2, GlobalVariable.login_currency)
ExcelKeywords.setValueToCellByAddress(login, 'D1', 'partner_code')
ExcelKeywords.setValueToCellByIndex(login, j, 3, GlobalVariable.partner_code)
ExcelKeywords.setValueToCellByAddress(login, 'E1', 'player_id')
ExcelKeywords.setValueToCellByIndex(login, j, 4, GlobalVariable.player_id)
ExcelKeywords.setValueToCellByAddress(login, 'F1', 'game_code')
ExcelKeywords.setValueToCellByIndex(login, j, 5, GlobalVariable.login_game_code)
ExcelKeywords.setValueToCellByAddress(login, 'G1', 'bet_amount')
ExcelKeywords.setValueToCellByIndex(login, j, 6, GlobalVariable.login_bet_amount)
ExcelKeywords.setValueToCellByAddress(login, 'H1', 'bet_value')
ExcelKeywords.setValueToCellByIndex(login, j, 7, GlobalVariable.login_bet_value)
ExcelKeywords.setValueToCellByAddress(login, 'I1', 'causality')
ExcelKeywords.setValueToCellByIndex(login, j, 8, GlobalVariable.login_causality)
ExcelKeywords.setValueToCellByAddress(login, 'J1', 'reels')
ExcelKeywords.setValueToCellByIndex(login, j, 9, GlobalVariable.login_reels)
ExcelKeywords.setValueToCellByAddress(login, 'K1', 'reel_wins')
ExcelKeywords.setValueToCellByIndex(login, j, 10, GlobalVariable.login_reel_wins)
ExcelKeywords.setValueToCellByAddress(login, 'L1', 'features')
ExcelKeywords.setValueToCellByIndex(login, j, 11, GlobalVariable.features)
ExcelKeywords.setValueToCellByAddress(login, 'M1', 'features_triggered')
ExcelKeywords.setValueToCellByIndex(login, j, 12, GlobalVariable.login_features_triggered)
ExcelKeywords.setValueToCellByAddress(login, 'N1', 'scatter_win')
ExcelKeywords.setValueToCellByIndex(login, j, 13, GlobalVariable.login_state_scatter_win)
ExcelKeywords.setValueToCellByAddress(login, 'O1', 'engagements')
ExcelKeywords.setValueToCellByIndex(login, j, 14, GlobalVariable.login_engagements)
ExcelKeywords.setValueToCellByAddress(login, 'P1', 'win_amount')
ExcelKeywords.setValueToCellByIndex(login, j, 15, GlobalVariable.login_win_amount)
ExcelKeywords.setValueToCellByAddress(login, 'Q1', 'bet_per_line')
ExcelKeywords.setValueToCellByIndex(login, j, 16, GlobalVariable.login_bet_per_line)
ExcelKeywords.setValueToCellByAddress(login, 'R1', 'round_win')
ExcelKeywords.setValueToCellByIndex(login, j, 17, GlobalVariable.login_round_win)
ExcelKeywords.setValueToCellByAddress(login, 'S1', 'feature_win')
ExcelKeywords.setValueToCellByIndex(login, j, 18, GlobalVariable.login_feature_win)
ExcelKeywords.setValueToCellByAddress(login, 'T1', 'fraction')
ExcelKeywords.setValueToCellByIndex(login, j, 19, GlobalVariable.login_fraction)
ExcelKeywords.setValueToCellByAddress(login, 'U1', 'provider')
ExcelKeywords.setValueToCellByIndex(login, j, 20, GlobalVariable.login_provider)
ExcelKeywords.setValueToCellByAddress(login, 'V1', 'lines')
ExcelKeywords.setValueToCellByIndex(login, j, 21, GlobalVariable.login_lines)
ExcelKeywords.setValueToCellByAddress(login, 'W1', 'spin_config')
ExcelKeywords.setValueToCellByIndex(login, j, 22, GlobalVariable.login_auto_spin_config)
ExcelKeywords.setValueToCellByAddress(login, 'X1', 'denominations')
ExcelKeywords.setValueToCellByIndex(login, j, 23, GlobalVariable.login_bet_denominations)
ExcelKeywords.setValueToCellByAddress(login, 'Y1', 'numbe_of_lines')
ExcelKeywords.setValueToCellByIndex(login, j, 24, GlobalVariable.login_number_of_lines)
ExcelKeywords.setValueToCellByAddress(login, 'Z1', 'default_bet_denom_idx')
ExcelKeywords.setValueToCellByIndex(login, j, 25, GlobalVariable.login_default_bet_denom_idx)
ExcelKeywords.setValueToCellByAddress(login, 'AA1', 'paylines')
ExcelKeywords.setValueToCellByIndex(login, j, 26, GlobalVariable.login_paylines)
ExcelKeywords.setValueToCellByAddress(login, 'AB1', 'prefer_bet_per_line')
ExcelKeywords.setValueToCellByIndex(login, j, 27, GlobalVariable.bet_prefer_bet_per_line)
ExcelKeywords.setValueToCellByAddress(login, 'AC1', 'result_scatter_win')
ExcelKeywords.setValueToCellByIndex(login, j, 28, GlobalVariable.login_result_scatter_win)
// Save Data of Excel File
ExcelKeywords.saveWorkbook(excelFile01, workbook01)

// Set Spin Data to Excel Fiel
workbook01 = ExcelKeywords.getWorkbook(excelFile01)
take_turn = ExcelKeywords.getExcelSheet(workbook01, 'take_turn')
ExcelKeywords.setValueToCellByAddress(take_turn, 'A1', 'round_id')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 0, GlobalVariable.round_id)
ExcelKeywords.setValueToCellByAddress(take_turn, 'B1', 'balance')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 1, GlobalVariable.balance)
ExcelKeywords.setValueToCellByAddress(take_turn, 'C1', 'currency')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 2, GlobalVariable.currency)
ExcelKeywords.setValueToCellByAddress(take_turn, 'D1', 'partner_code')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 3, GlobalVariable.partner_code)
ExcelKeywords.setValueToCellByAddress(take_turn, 'E1', 'player_id')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 4, GlobalVariable.player_id)
ExcelKeywords.setValueToCellByAddress(take_turn, 'F1', 'game_code')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 5, GlobalVariable.game_code)
ExcelKeywords.setValueToCellByAddress(take_turn, 'G1', 'bet_amount')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 6, GlobalVariable.bet_amount)
ExcelKeywords.setValueToCellByAddress(take_turn, 'H1', 'bet_value')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 7, GlobalVariable.bet_value)
ExcelKeywords.setValueToCellByAddress(take_turn, 'I1', 'causality')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 8, GlobalVariable.causality)
ExcelKeywords.setValueToCellByAddress(take_turn, 'J1', 'reels')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 9, GlobalVariable.reels)
ExcelKeywords.setValueToCellByAddress(take_turn, 'K1', 'reel_wins')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 10, GlobalVariable.reel_wins)
ExcelKeywords.setValueToCellByAddress(take_turn, 'L1', 'features')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 11, GlobalVariable.features)
ExcelKeywords.setValueToCellByAddress(take_turn, 'M1', 'features_triggered')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 12, GlobalVariable.features_triggered)
ExcelKeywords.setValueToCellByAddress(take_turn, 'N1', 'scatter_win')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 13, GlobalVariable.scatter_win)
ExcelKeywords.setValueToCellByAddress(take_turn, 'O1', 'engagements')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 14, GlobalVariable.engagements)
ExcelKeywords.setValueToCellByAddress(take_turn, 'P1', 'win_amount')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 15, GlobalVariable.win_amount)
ExcelKeywords.setValueToCellByAddress(take_turn, 'Q1', 'bet_per_line')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 16, GlobalVariable.bet_per_line)
ExcelKeywords.setValueToCellByAddress(take_turn, 'R1', 'round_win')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 17, GlobalVariable.round_win)
ExcelKeywords.setValueToCellByAddress(take_turn, 'S1', 'feature_win')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 18, GlobalVariable.feature_win)
ExcelKeywords.setValueToCellByAddress(take_turn, 'T1', 'fraction')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 19, GlobalVariable.fraction)
ExcelKeywords.setValueToCellByAddress(take_turn, 'U1', 'provider')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 20, GlobalVariable.provider)
ExcelKeywords.setValueToCellByAddress(take_turn, 'V1', 'lines')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 21, GlobalVariable.lines)
ExcelKeywords.setValueToCellByAddress(take_turn, 'W1', 'result_scatter_win')
ExcelKeywords.setValueToCellByIndex(take_turn, j, 22, GlobalVariable.spin_result_scatter_win)
// Save Data of Excel File
ExcelKeywords.saveWorkbook(excelFile01, workbook01)
